### ISSUE TITLE
Rename "size" to "statusSize"

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-bitstring-status-list#113]
`size` is actually the size of the status, not the size of the list, as it is presently modeled. This is misnamed/mismodeled and should probably become `statusSize`.

**Comment by msporny** [comment]
Should it be `statusEntrySize` instead? Given that we have multibit entries now, I've been trying to figure out how to reformulate the specification to convey that concept. Other words include "item" and "element".

**Comment by dlongley** [comment]
Well, to me, "status entry" makes me think of a `BitstringStatusEntry` which is something else from the status value itself. If `statusSize` doesn't work, perhaps `statusValueSize` ... but I don't know that we need the extra word.

**Comment by dlongley** [comment]
I'll note that we currently use `status` to express (in hex) status values in `statusMessage`, which, I believe, means `statusSize` (or `statusValueSize` if we want the longer name) makes sense.

**Comment by msporny** [comment]
The fix has been applied in PR #109. This issue will be closed once PR #109 has been merged.

**Comment by msporny** [comment]
PR #109 has been merged, closing.
