### ISSUE TITLE
Rename `reference` to `statusReference`

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-bitstring-status-list#114]
`reference` is not a reference for the list, but for the status (or statuses). The main use case envisaged at the moment is for a dictionary of statuses / status messages. This should be renamed to `statusReference` on that basis. If there's only one use case that really makes sense, and it's a status dictionary, then we could rename it `statusDictionary` and provide a fuller example.

_Originally posted by @dlongley in https://github.com/w3c/vc-bitstring-status-list/pull/109#discussion_r1438400646_

**Comment by msporny** [comment]
The fix has been applied in PR #109. This issue will be closed once PR #109 has been merged.

**Comment by msporny** [comment]
PR #109 has been merged, closing.
