### ISSUE TITLE
Encoding of `statusListIndex`

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-bitstring-status-list#134]
2.1 BitstringStatusListEntry
https://w3c.github.io/vc-bitstring-status-list/#bitstringstatuslistentry

> The statusListIndex property MUST be an arbitrary size integer greater than or equal to 0, expressed as a string.

Probably this should mention how "expressed as a string" is encoded a bit more clearly. In particular, is the number decimal or hex?

(This issue was found as part of the I18N review, but is not an I18N issue, hence the `-tracker` label)

**Comment by OR13** [comment]
perhaps:

> be an arbitrary size integer greater than or equal to 0, expressed as a string in base 10.

**Comment by msporny** [comment]
PR #137 was raised to address this issue. This issue will be closed once that PR is merged.

**Comment by msporny** [comment]
PR #137 has been merged, closing.
