### ISSUE TITLE
`statusPurpose` type `message` unclear

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-bitstring-status-list#135]
2.1 BitStringStatusListEntry
https://w3c.github.io/vc-bitstring-status-list/#bitstringstatuslistentry

> Used to convey an arbitrary message related to the status of the verifiable credential.

There is a field called `statusPurpose` which can take three values: `revocation`, `suspension`, and `message`. The first two purposes are clear, but the last one implies that some kind of message (which might be a natural language string?!?) is meant to be communicated. There are no examples of this last status, so it is difficult to tell if international string metadata or other considerations apply here. This could be clearer.

Later on the `credentialSubject.statusPurpose` that has a `message` type and invokes `credentialSubject.statusMessage` as a container for messages. There is a separate issue about those messages.

**Comment by OR13** [comment]
There are examples, see https://w3c.github.io/vc-bitstring-status-list/#example-example-bitstringstatuslistcredential-0

```
...
    "statusPurpose": "status",
    "statusReference": "https://example.org/status-dictionary/",
    "statusSize": 2,
    "statusMessage": [
        {"status":"0x0", "message":"valid"},
        {"status":"0x1", "message":"invalid"},
        {"status":"0x2", "message":"pending_review"},
        ...
    ],
    "encodedList": "uH4sIAAAAAAAAA-3BMQEAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAIC3AYbSVKsAQAAA"
  }
```

AFAIK, all string data types in JSON-LD have the following internationalization considerations:

https://www.w3.org/TR/json-ld11/#string-internationalization

Perhaps a reference to this, done once at the beginning of the spec would address this for all instances of strings in the data model.

**Comment by msporny** [comment]
PR #138 was raised, discussed, and merged to address this issue. There are now examples of status messages in the spec as well as guidance that they are to be used by software developers only and SHOULD NOT be exposed to end users. Closing.
