### ISSUE TITLE
Processing error `title` and `detail` need lang/dir guidance

### ISSUE THREAD

**Issue by aphillips** [w3c/vc-bitstring-status-list#140]
Section 3.5 Processing Errors
https://w3c.github.io/vc-bitstring-status-list/#processing-errors

> - The `title` value SHOULD provide a short but specific human-readable string for the error.
> - The `detail` value SHOULD provide a longer human-readable string for the error. 

The section on processing errors describes using the `statusList` to encode error information. Each error type is given an integer value, which is also named. For example **`STATUS_RETRIEVAL_ERROR (-128)`**. In addition, the errors are provided with a `title` and `description` field with the description quoted just above.

Ideally these human-readable strings would have language and direction metadata, either directly in `statusList` or encoded at the document level. See particularly our guidance here: https://www.w3.org/TR/international-specs/#loc_localization

Encoding at the document level would make sense for errors (and other uses of `statusList`), since the status is likely to be in the transaction's or credential's negotiated language. If the use of language/direction for bitstring processing relies on data model, there should probably be a note about language in this section stating something about "specific human-readable string" or "longer human-readable string" and pointing to the [same location](https://www.w3.org/TR/vc-data-model-2.0/#internationalization-considerations) as your internationalization considerations section. Otherwise it isn't clear how `title` and `detail` encode the metadata.

(Note: this issue is the last in our horizontal review)

**Comment by aphillips** [comment]
https://www.w3.org/2024/02/08-i18n-minutes.html#t08

**Comment by msporny** [comment]
@aphillips would I18N be okay w/ using the guidance here: https://www.rfc-editor.org/rfc/rfc9457#section-1

Specifically, 

> When they are conveyed in an HTTP response, the contents of problem details can be negotiated using proactive negotiation; see [Section 12.1](https://www.rfc-editor.org/rfc/rfc9110#section-12.1) of [[HTTP](https://www.rfc-editor.org/rfc/rfc9457#RFC9110)]. In particular, the language used for human-readable strings (such as those in title and description) can be negotiated using the Accept-Language request header field ([Section 12.5.4](https://www.rfc-editor.org/rfc/rfc9110#section-12.5.4) of [[HTTP](https://www.rfc-editor.org/rfc/rfc9457#RFC9110)]), although that negotiation may still result in a non-preferred, default representation being returned.

The processing errors are meant to be conveyed via HTTP or via a software library to a developer. They are not meant to be exposed to non-developers.

**Comment by aphillips** [comment]
Yes, when returning values in a header like that, you absolutely can reference language negotiation, including RFC9547. There is no requirement that a given request be localized into all languages everywhere--or localized at all, for that matter. Indicating that language negotiation based on Accept-Language is what should happen might take the form of a note in your spec.

> The processing errors are meant to be conveyed via HTTP or via a software library to a developer. They are not meant to be exposed to non-developers.

Understood. I18N notes that developers are people too. Also, such error messages sometimes _do_ get shown to non-developer users, in spite of specifications saying that they shouldn't be 😉 

FWIW, our guidance lives [here](https://www.w3.org/TR/international-specs/#errors) and is consistent with your proposal.

Thanks!

**Comment by msporny** [comment]
PR #152 has been raised to address this issue. This issue will be closed once PR #152 has been merged.

**Comment by msporny** [comment]
PR #152 has been merged, closing.
