### ISSUE TITLE
Remove open ended status messages because it is a layer violation

### ISSUE THREAD

**Issue by jandrieu** [w3c/vc-bitstring-status-list#151]
In discussing issue #146, @msporny clarified that the current bitstring status list supports arbitrary messages in status lists.

Unfortunately, this turns status lists into yet another attestation architecture, which is a layering violation. Status lists don't have the privacy and security features we have for VCs, which is where, in the VC architecture, issuers make formal attestations about subjects.

Bitstring status lists should be used to enable decentralized verification of pre-arranged possible statuses, not of arbitrary, potentially changing attributes of the subject.

**Comment by msporny** [comment]
@jandrieu Given that the specification has already marked the status messages feature as "at risk", and is seeking implementer feedback during CR, do you see this issue as potentially blocking our transition to CR next month?

**Comment by brentzundel** [comment]
Isn't status returned as a VC? That would mean Status lists are using the VC attestation architecture which has precisely the privacy and security features we have for VCs.

The trouble with our WG trying to pre-arrange every possible status is that we can't possibly get them all. Why shouldn't a status VC have extension points just like a regular VC?

Perhaps it needs to be clarified that the subject of a status VC is always another credential, therefore any messages in a status VC are only ever messages about the status of the VC, not about the subject of the original VC.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2024-03-27-vcwg#section2-1) on 2024-03-27

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 2.1. Remove open ended status messages because it is a layer violation (issue vc-bitstring-status-list#151)

_See github issue [vc-bitstring-status-list#151](https://github.com/w3c/vc-bitstring-status-list/issues/151)._




**Manu Sporny:** PING have raised several privacy issues that we should address.  
… several issues around I18N that need to be reviewed.  
… strings may be human readable.  

> *Manu Sporny:* [https://github.com/w3c/vc-data-model/pulls](https://github.com/w3c/vc-data-model/pulls).

**Manu Sporny:** will be a massive PR to address Yaskin's comments.  
… mostly editorial apart from a few normative statements (but no new implementation requirements).  

</details>

**Comment by jandrieu** [comment]
> Isn't status returned as a VC? That would mean Status lists are using the VC attestation architecture which has precisely the privacy and security features we have for VCs.

Unfortunately the status list architecture does not have the same privacy and security features as VCs, because the holder is not involved in the status check. That check bypasses holder control, which is a key component of the VC privacy architecture.

> The trouble with our WG trying to pre-arrange every possible status is that we can't possibly get them all. Why shouldn't a status VC have extension points just like a regular VC?

Agreed. We don't need to come up with all possible statuses, but the possible statuses of a given credential, IMO, should be set at the time of issuance and not changing over time.

The idea that we might restrict status results to a particular subject, e.g., that of the credential, is a good idea, but I think only half-way there.

The problem is that there is no way to enforce that.

If issuers have a set of known states they want to dynamically update, they can do that with a static set of states. That addresses a wide range of legitimate use cases without needing to enable open-ended assertions through the status list.

What we don't want issuers to do is to use the status list as a mechanism to publish arbitrary content about the subject of a VC without that subject being involved in the distribution of that content.

**Comment by msporny** [comment]
PR #164 has been raised to address this issue. This issue will be closed once PR #164 is merged.

**Comment by msporny** [comment]
PR #164 has been merged, closing.
