### ISSUE TITLE
Make the generated vocabulary file available for preview

### ISSUE THREAD

**Issue by iherman** [w3c/vc-bitstring-status-list#157]
On the data model and DI repositories it is possible to see the generated vocabulary file via, say,

https://w3c.github.io/vc-data-model/vocab/credentials/v2/vocabulary.html

This is done via some github action magic. The same should be done in this repository to see the generated voabulary file via

https://w3c.github.io/vc-bitstring-status-list/vocab/vocabulary.html

**Comment by iherman** [comment]
@msporny, you assigned me to this issue, but I would prefer you do the changes, because changing actions is a sensitive area, and I am not sure to have the right experience. I have compared the repo with the data integrity repository, and I see two differences that, most probably, make the difference. These are:

- In the `settings/Pages` the `di-data-integrity` repo says that the source of the build & deployment are github actions. I would think the same should be used in the current repo, which is not the case (it says to deploy from a branch). I presume that, under the current settings, the `gh-pages.yml` action has no effect (it is, otherwise an almost carbon copy of the action for `di-data-integrity` action, except for the path to the vocabulary files.
- The `di-data-integrity` repo has a separate action called `lint-vocab.yml`, which is used to check the vocabulary. I would think that should be copied here with the obvious change of `vocab/security/`➝`vocab/` in the path of the command in the last line.

Would you do these changes if you agree with them?

Also: once this is done, we also have to set up an alias for `https://www.w3.org/ns/credentials/status` to point to the vocabulary. I hope that will happen without problems as it is, although it may be easier to do it with `https://www.w3.org/ns/credentials/status/`...

**Comment by msporny** [comment]
PR #165 has been merged. Applying the vocabulary generation stuff via Github Actions now.

**Comment by msporny** [comment]
The publication via workflow works now:

https://w3c.github.io/vc-bitstring-status-list/vocab/vocabulary.html

**Comment by iherman** [comment]
For the records, the URL redirections mentioned in https://github.com/w3c/vc-bitstring-status-list/issues/157#issuecomment-2031760132 have been set up in `www.w3.org/ns/credentials`.

cc @msporny
