### ISSUE TITLE
(Editorial) Add border lines (or use different colors) to table rows

### ISSUE THREAD

**Issue by iherman** [w3c/vc-bitstring-status-list#169]
I find the specification of the properties in [§2.1 BitstringStatusListEntry](https://www.w3.org/TR/vc-bitstring-status-list/#bitstringstatuslistentry) very difficult to read, because it is not clear where, for example, the definition in the right column for `id` ends and `type` begins. Please use some visual clues (borders, background color, etc) to overcome this.

**Comment by iherman** [comment]
I have checked the html source, and I must admit I am a bit lost. The source uses the same `class="simple"` attribute for tables as, say, the VC JSON Schema document does, but the rendering is different. At first glance, I did not see any difference in the respec setup or the included files. I cannot explain what I see, but the editors may know this...

ping @msporny @mkhraisha

**Comment by msporny** [comment]
Older versions of ReSpec had a "simple" table class. That has been removed, for whatever reason. I added the missing CSS classes back in for simple tables to make it easier to read.

I have fixed this in commit 47e190054247139583bfe2cebdf7d0e6c152bdb7. Closing.
