### ISSUE TITLE
Clarification on statusListIndex type

### ISSUE THREAD

**Issue by robdefeo** [w3c/vc-bitstring-status-list#177]
The spec indicates that `statusListIndex` is an integer. https://github.com/w3c/vc-bitstring-status-list/blob/47e190054247139583bfe2cebdf7d0e6c152bdb7/index.html#L587-L592

However the examples show it as a string, https://github.com/w3c/vc-bitstring-status-list/blob/47e190054247139583bfe2cebdf7d0e6c152bdb7/index.html#L696

There is an important difference when it comes to creating the verification data

`_:c14n1 <https://www.w3.org/ns/credentials/status#statusListIndex> "94567"^^<http://www.w3.org/2001/XMLSchema#integer> .`

vs

`_:c14n1 <https://www.w3.org/ns/credentials/status#statusListIndex> "94567" .`

Acceptance criteria is confirming the correct behaviour and correcting the text or the examples.

**Comment by PatStLouis** [comment]
The spec specifies that this integer is expressed as a string in base 10. If you feel this should be worded differently feel free to propose an alternate wording here for feedback.

> The `statusListIndex` property MUST be an arbitrary size integer greater than or equal to 0, **expressed as a string in base 10**.

**Comment by robdefeo** [comment]
You are correct, I miss-read/missed that part of the spec. On re-reading the spec is clear. 

Thanks @PatStLouis for the graceful explanation.
