### ISSUE TITLE
Inconsistent algorithm and data model for encodedList

### ISSUE THREAD

**Issue by PatStLouis** [w3c/vc-bitstring-status-list#178]
The BitstringStatusListCredential data model defines the encodedList as follows:

> The encodedList property of the credential [subject](https://www.w3.org/TR/vc-data-model-2.0/#dfn-subjects) MUST be a [Multibase-encoded base64url (with no padding)](https://www.w3.org/TR/vc-data-integrity/#multibase-0) [[RFC4648](https://www.w3.org/TR/vc-bitstring-status-list/#bib-rfc4648)] representation of the GZIP-compressed [[RFC1952](https://www.w3.org/TR/vc-bitstring-status-list/#bib-rfc1952)] bitstring values for the associated range of [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) status values.

The Bitstring Generation Algorithm gives the following instruction:

> Generate a compressed bitstring by using the GZIP compression algorithm [[RFC1952](https://www.w3.org/TR/vc-bitstring-status-list/#bib-rfc1952)] on the bitstring and then base64url-encoding (with no padding) [[RFC4648](https://www.w3.org/TR/vc-bitstring-status-list/#bib-rfc4648)] the result.

I suggest to add instruction to produce a [Multibase-encoded base64url (with no padding)](https://www.w3.org/TR/vc-data-integrity/#multibase-0) [[RFC4648](https://www.w3.org/TR/vc-bitstring-status-list/#bib-rfc4648)] representation of the GZIP-compressed [[RFC1952](https://www.w3.org/TR/vc-bitstring-status-list/#bib-rfc1952)] bitstring value to the algorithm.

**Comment by msporny** [comment]
PR #179 has been merged to address this issue, closing.
