### ISSUE TITLE
Remove integer codes from problemDetails

### ISSUE THREAD

**Issue by PatStLouis** [w3c/vc-bitstring-status-list#180]
Following the [removal of error integer codes from the vcdm 2.0 specification](https://github.com/w3c/vc-data-model/pull/1562), this specification should also remove normative statements and references about `problemDetails` integer codes.

**Comment by msporny** [comment]
PR #181 has been raised to address this issue. This issue will be closed once PR #181 has been merged.

**Comment by msporny** [comment]
PR #181 has been merged, closing.
