### ISSUE TITLE
Hosting of the bitstring status list context

### ISSUE THREAD

**Issue by chumbert** [w3c/vc-bitstring-status-list#182]
Hello, I have a small question on referencing the Bitstring Status List context in VCDM 1.0 credentials:

With https://github.com/w3c/vc-bitstring-status-list/issues/91 and https://github.com/perma-id/w3id.org/pull/3662, we can refer to the `Status List 2021` context through w3c perma-ids.

I am under the impression however that this same change prevents referencing the bistring status list context that's here: https://github.com/w3c/vc-bitstring-status-list/blob/main/contexts/v1.jsonld

Is this second context intended to be hosted too, should implementers that use VCDM 1.0 with bitstring status lists reference it from somewhere else, or am I simply missing the correct url to reference it ?

Kind regards.

**Comment by msporny** [comment]
> Is this second context intended to be hosted too

Yes.

> should implementers that use VCDM 1.0 with bitstring status lists reference it from somewhere else, or am I simply missing the correct url to reference it ?

We haven't set the correct URL to reference it yet, it will likely be something like:

`https://www.w3.org/ns/credentials/bitstring-status-list/v1`

but we expect most people to use the v2.0 context, `https://www.w3.org/ns/credentials/v2`, which includes it by default:

https://github.com/w3c/vc-data-model/blob/main/contexts/credentials/v2#L142-L202

Does this answer your question?

If so, I'm going to keep this issue open because we do need to:

1. Decide what that URL is going to be for v1.0 and v1.1 VCs, and
2. Make sure the context matches the v2 context *and* actually publish it at the corresponding URL.

**Comment by chumbert** [comment]
Thank you, this does answer my question. I'll keep an eye on this then.

**Comment by msporny** [comment]
> Decide what that URL is going to be for v1.0 and v1.1 VCs, and

It's going to be this URL:

`https://www.w3.org/ns/credentials/bitstring-status-list/v1`

> Make sure the context matches the v2 context 

This has been done

>  actually publish it at the corresponding URL.

This has not been done yet, but won't happen until we publish the Proposed Recommendation. I'll leave the issue open until that happens.

**Comment by msporny** [comment]
@iherman I'm assigning this one to you because you're the one that will need to publish the JSON-LD context to `https://www.w3.org/ns/credentials/status/v1`

**Comment by iherman** [comment]
Done. See:

```
9:14 ivan> curl --head https://www.w3.org/ns/credentials/status/v1
HTTP/2 200
date: Mon, 02 Dec 2024 08:15:16 GMT
content-type: application/ld+json
permissions-policy: interest-cohort=()
last-modified: Sat, 30 Nov 2024 21:46:04 GMT
access-control-allow-origin: *
etag: W/"674b879c-73f"
expires: Mon, 02 Dec 2024 08:25:16 GMT
...
9:15 ivan> curl https://www.w3.org/ns/credentials/status/v1
{
  "@context": {
    "@protected": true,

    "BitstringStatusListCredential": "https://www.w3.org/ns/credentials/status#BitstringStatusListCredential",
    ...
}
```

**Comment by msporny** [comment]
The latest context has been published at `https://www.w3.org/ns/credentials/status/v1`. Closing.
