### ISSUE TITLE
Shouldn’t there be a reference to the vocabulary and context files?

### ISSUE THREAD

**Issue by iherman** [w3c/vc-bitstring-status-list#188]
Other specs, like the controller document, have a section on the fact that the terms in the spec are defined in a specific formal vocabulary, and the terms are part of a specific context (or contexts). This information should be presen in this spec, too, imho.

**Comment by msporny** [comment]
PR #189 has been raised to address this issue. This issue will be closed once PR #189 has been merged.

**Comment by msporny** [comment]
PR #189 has been merged, closing.
