### ISSUE TITLE
Randomization

### ISSUE THREAD

**Issue by OR13** [w3c/vc-bitstring-status-list#41]
Should bitstring be initialized randomly, (reduces compression).

Should bitstring be consumed randomly, (implementation burden on the issuer).

**Comment by dlongley** [comment]
My initial vote is for the latter (issuers should assign indexes in a pseudo-random fashion).

There are probably a lot of use cases where very few bits would be flipped -- and it would probably be significantly more costly across an ecosystem and over time to increase the size of lists vs. requiring implementers to do a bit more work (ideally once).

**Comment by msporny** [comment]
PR #92 has been merged, closing.
