### ISSUE TITLE
Would like multiple status to be capable of representation in a status list

### ISSUE THREAD

**Issue by mprorock** [w3c/vc-bitstring-status-list#42]
if instead of a bit, a `size` of the status is defined, and a set of codes attached to status values is provided we could easily represent multiple types of status, rather than requiring checking multiple lists

**Comment by dlongley** [comment]
I'd question whether everyone would agree on "easily" :).

It may be better to keep the basic list primitive simple and just use composition on top of that as we do today. There are other considerations with changing it -- including the compression characteristics and, perhaps, privacy threat analysis.

**Comment by dlongley** [comment]
See: https://github.com/w3c/vc-status-list-2021/issues/37#issuecomment-1416348418

**Comment by msporny** [comment]
This feature landed in PR #65, closing.
