### ISSUE TITLE
Is it possible to support multiple purposes?

### ISSUE THREAD

**Issue by echenknox** [w3c/vc-bitstring-status-list#47]
In VC, it defines only one `credentialStatus`,
```
{
  "@context": {
    "@version": 1.1,
    "@protected": true,

    "VerifiableCredential": {
      "@id": "https://www.w3.org/2018/credentials#VerifiableCredential",
      "@context": {
        "@version": 1.1,
        "@protected": true,
        // ... omitted ...
        "credentialStatus": {"@id": "cred:credentialStatus", "@type": "@id"},
        // ... omitted ...
```

Then in StatusList, it defines only one `purpose`, either "revocation" or "suspension". Is there a possibility one may want to have 2 purposes in one credential?

```
{
  "@context": {
    "@protected": true,

    "StatusList2021": {
      "@id":
        "https://w3id.org/vc/status-list#StatusList2021",
      "@context": {
        "@protected": true,

        "id": "@id",
        "type": "@type",

        "statusPurpose":
          "https://w3id.org/vc/status-list#statusPurpose",
        "encodedList": "https://w3id.org/vc/status-list#encodedList"
      }
    }
   // ... omitted ...
```

**Comment by echenknox** [comment]
Related to this [issue](https://github.com/w3c/vc-status-list-2021/issues/42).

**Comment by echenknox** [comment]
If there's only one status in a VC, this is how the status can be used.
1. When the VC was first issued, the issuer had to add a status "suspension" in the VC.
2. The issuer calls Verifiable Credential Registry to reserve an index for this VC. However, it leaves the bit value as 0. 
     It can't wait to add suspension when the issuer wants to suspend a VC. Once the holder receives VC, it caches VC. If the holder has a VC without status, the verifier will never know where to check the status. 
     It can use "revocation" as the initial status. Since the specification is very vague on how this should be used, I assume "suspension=0" is the initial status because "revocation" is irreversible.
3. If the issuer needs to revoke a VC, it updates the Verifiable Credential Registry. 
    When the holder sends VC to a verifier, the verifier checks the "StatusList2021Entry", retrieves "StatusList2021Credential" and verifies the revocation status.

One problem here is that if the initial StatusList2021Entry added in a VC is using "suspension" as the "purpose",  then the issuer sets the status to "revocation." The issuer can't change the "StatusList2021Entry" to the VC that is already issued to a holder. The status validation will fail (according to this [algorithm](https://w3c.github.io/vc-status-list-2021/#validate-algorithm)).

Feels like when an issuer issues a type of VC, it has to decide which "purpose" in the status to use, then it can never change to another purpose.

**Comment by dlongley** [comment]
See: https://github.com/w3c/vc-status-list-2021/issues/37#issuecomment-1416348418 for an example of multiple status entries in a VC.

**Comment by OR13** [comment]
https://github.com/w3c-ccg/vc-api/issues/225

As an example of an API to update multiple purposes.

**Comment by msporny** [comment]
The answer to the initial question is: yes, it's possible to support multiple purposes.

There are two mechanisms to do this that the specification supports today:

1. Associate an array with `credentialStatus`, where each object of the array contains a different purpose, or
2. Use the multibit status message mechanism.

Given that the specification supports both of these approaches today (and the latest PRs make that more evident), I'm marking this issue as pending 7 day close.
