### ISSUE TITLE
Document design characteristics why "StatusList2021Entry" is signed.

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-bitstring-status-list#49]
to reduce an attack surface.

and because StatusListCredential is a URL (includes URIs in WHAT WG definition) and it is not always WebPKI..?

**Comment by msporny** [comment]
PR #162 has been raised to address this issue. This issue will be closed once PR #162 has been merged.

**Comment by msporny** [comment]
PR #162 has been merged, closing.
