### ISSUE TITLE
Implementation guidelines around how StatusList2021Credential is secured/encoded.

### ISSUE THREAD

**Issue by Sakurann** [w3c/vc-bitstring-status-list#52]
there are multiple ways to secure a VC that is a `StatusList2021Credential`.

How does the verifier know whether it is JWS or linked data proof, which cryptosuite it is beforehand? In other words, how to ensure that the verifier actually can verify the `StatusList2021Credential`? 

I think it is up to the trust framework/protocol, but implementation guidelines saying that this metadata needs to be obtained should be useful.

**Comment by OR13** [comment]
Similar to how Verifiable Credentials don't signal the proof type, I think this is unknowable...

It would be a best practice to:

1. Not mix JWT and data integrity proofs
2. Not different crypto in the same securing format.

The spec should make these recommendations.

**Comment by msporny** [comment]
PR #118 has been raised to address this issue (which applies the guidance provided by @OR13 above). This issue will be closed once PR #118 has been merged.

**Comment by msporny** [comment]
PR #118 has been merged, closing.
