### ISSUE TITLE
Media type pairings

### ISSUE THREAD

**Issue by OR13** [w3c/vc-bitstring-status-list#78]
There will be problems with media type processing for status list 2021...

Specifically cross media type dependencies:
- where `vc+ld+jwt` uses a `vc+ld+json` status list
- where `vc+ld+json` uses a `vc+ld+jwt` status list

The status list spec should address this, 
by acknowledging the registered media types, and recommending against "mixing" of media types.

**Comment by mprorock** [comment]
agreed - otherwise things will get very ugly

**Comment by msporny** [comment]
PR #92 has been merged, closing.
