### ISSUE TITLE
Section 4.3 should be improved to suggest utilization of OHTTP to prevent correlation

### ISSUE THREAD

**Issue by kdenhartog** [w3c/vc-bitstring-status-list#80]
While content networks can be useful there's an inherent trust on the third party CDN to behave and not provide access to the information. Now that OHTTP is more mature, resolution should be encouraged over an OHTTP channel to prevent linking the verifier of the list to an IP address. This prevents correlation of the IP address to the resolution of the credential improving privacy.

https://ietf-wg-ohai.github.io/oblivious-http/draft-ietf-ohai-ohttp.html

**Comment by Sakurann** [comment]
I understand the preference for OHTTP, but `more mature` is not sufficient to normatively point to it yet, IMO - it is not an RFC yet. I might be comfortable with saying "OHTTP should be used once it becomes an RFC"

**Comment by kdenhartog** [comment]
This is in a non normative section so wouldn't be normatively referenced was what I had in mind. I agree that this definitely should not be a normative requirement though. That effectively means everyone has to use cloudflare spectrum since AFAIK they're the only company offering the intermediary service so far.

**Comment by msporny** [comment]
PR #107 has been raised to address this issue. This issue will be closed once PR #107 has been merged.

**Comment by OR13** [comment]
This issue should be closed, the PR was merged.

The current text contradicts the JWT BCP.

**Comment by msporny** [comment]
PR #107 has been merged, closing.
