### ISSUE TITLE
Should validation algorithm check size of bitstring?

### ISSUE THREAD

**Issue by andresuribe87** [w3c/vc-bitstring-status-list#87]
The section in https://w3c.github.io/vc-status-list-2021/#validate-algorithm does not mention checking the minimum bitstring size.

Suggestion is that validation should fail when the size of the bitstring is below the minimum of 16KB.

**Comment by msporny** [comment]
PR #115 has been raised to address this issue. This issue will be closed once PR #115 has been merged.

**Comment by msporny** [comment]
PR #115 has been merged, closing.
