### ISSUE TITLE
Status-List-2021 LD-Context broken

### ISSUE THREAD

**Issue by F-Node-Karlsruhe** [w3c/vc-bitstring-status-list#91]
https://w3id.org/vc/status-list/2021/v1 is redirecting to https://w3c.github.io/vc-status-list-2021/contexts/v1.jsonld which returns 404

**Comment by msporny** [comment]
Sorry, missed the initial request. 

The PR is in, we're trying to move it through the system as quickly as we can: https://github.com/perma-id/w3id.org/pull/3662

We didn't know anyone was using this in a production capacity. Good to know. We'll be more careful w/ renames in the future as a result.

**Comment by msporny** [comment]
> Is there a quick fix for this issue?

Yes, fixed -- https://w3id.org/vc/status-list/2021/v1 resolves again. As a warning, we might change the name of the spec one more time over the next week or two. If we do that, we'll make sure to do the w3id.org change at the same time this time.

The real fix here is to cache contexts (permanently) when you roll stuff like this into production. We have a part of the new VC v2.0 spec that speaks to this now: https://www.w3.org/TR/vc-data-model-2.0/#base-context

Namely, this text:

> It is considered a best practice to ensure that the same sorts of protections are provided for any URL that is critical to the security of the [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) through the use of permanently cached files and/or cryptographic hashes.

**Comment by msporny** [comment]
As a warning, we might change the name of the spec one more time over the next week or two. If we do that, we'll make sure to do the w3id.org change at the same time this time.

The real fix here is to cache contexts (permanently) when you roll stuff like this into production. We have a part of the new VC v2.0 spec that speaks to this now: https://www.w3.org/TR/vc-data-model-2.0/#base-context

Namely, this text:

> It is considered a best practice to ensure that the same sorts of protections are provided for any URL that is critical to the security of the [verifiable credential](https://www.w3.org/TR/vc-data-model-2.0/#dfn-verifiable-credential) through the use of permanently cached files and/or cryptographic hashes.

**Comment by victormartinez-work** [comment]
Many thanks for your fast response
