### ISSUE TITLE
Precise timestamps of status changes

### ISSUE THREAD

**Issue by decentralgabe** [w3c/vc-bitstring-status-list#94]
We have a use case to determine the time when the status of a given credential has changed. Without drastically changing the spec this can only be done if status list credentials have a validity window (valid from / valid until).

With a validity window, and consistent fetching (at the windows expiry) of status lists one could determine that a bit had flipped within a given window, and be able to approximate a timestamp of a given status change.

To make this type of query simpler I suggest adding language to the spec that speaks to the (optional) capability of a status list server to support historical queries, or revisions of the document from a given time period. I believe this would maintain the privacy preserving characteristics of the specification while adding the ability for verifiers to approximate status change time, which is useful in a number of circumstances.

**Comment by msporny** [comment]
PR #112 has been raised to address this issue. This issue will be closed once PR #117 has been merged.

**Comment by msporny** [comment]
PR #112 has been merged, closing.
