### ISSUE TITLE
Credential Type Mismatch between the Spec and the Schema

### ISSUE THREAD

**Issue by hkny** [w3c/vc-bitstring-status-list#96]
Hello,

there is a mismatch between the type used in the spec and the types allowed in the schema.

The spec has non-normative examples with the type `BitstringStatusList` (see [Example 2](https://www.w3.org/TR/vc-bitstring-status-list/#example-example-bitstringstatuslistcredential))

Non of the examples has a context, specifically defined for the BitstringStatusList. The closest is the one for [Status List 2021](https://w3id.org/vc/status-list/2021/v1).

As you can see, the schema does not have the type `BitstringStatusList`, causing JSON-LD validation error. Is there another schema that is supposed to be used together with the BitstringStatusList? If not, either the spec or the schema must be changed to ensure that the JSON-LD can be validated. 

Thanks.
Hakan

**Comment by msporny** [comment]
Yes, agreed. The VCWG renamed the specification to `BitstringStatusList`, so we will need to update all of the examples and schemas to match. This will be done over the next several weeks.

**Comment by msporny** [comment]
There are now PRs that address the initial issue raised, namely:

* #105
* #109 
* and https://github.com/w3c/vc-data-model/pull/1406

This issue will be closed once #109 and https://github.com/w3c/vc-data-model/pull/1406 are merged.

**Comment by msporny** [comment]
PRs #109 and w3c/vc-data-model#1406 are merged, closing.

**Comment by nitin-vavdiya** [comment]
Hey 
Recently, the response of https://w3id.org/vc/status-list/2021/v1 is again changed to an older one. 

Are there any URL changes?
