### ISSUE TITLE
Verification algorithm should say what happens if schema isn't followed

### ISSUE THREAD

**Issue by jyasskin** [w3c/vc-bitstring-status-list#97]
https://www.w3.org/TR/vc-bitstring-status-list/#validate-algorithm assumes that there's exactly one `statusPurpose`, `statusListCredential`, `statusPurpose`, `encodedList`, and `statusListIndex` property in their respective containers and that they have the expected types. If that's not true, the algorithm should say what to do (probably return `false`/"this credential isn't valid").

**Comment by msporny** [comment]
PR #116 has been raised to address this issue. This issue will be closed once PR #116 has been merged.

**Comment by msporny** [comment]
PR #116 has been merged, closing.
