### ISSUE TITLE
Invalid JSON in Example 1

### ISSUE THREAD

**Issue by samuelmr** [w3c/vc-bitstring-status-list#98]
The Example 1 (both in the published [Working Draft](https://www.w3.org/TR/vc-bitstring-status-list/#bitstringstatuslistentry) and the [Editor's draft](https://w3c.github.io/vc-bitstring-status-list/#bitstringstatuslistentry) is invalid JSON. A comma is missing after both `"id"` properties within the `"credentialStatus"` array. 

```json
 "id": "https://example.com/credentials/status/3#94567"
 "type": "BitstringStatusListEntry",
```

(I'm not a member or an invited expert but I don't think this counts as a substantive contribution.)

**Comment by msporny** [comment]
Thank you! Fixed in d10a8aa8a8227cdf5bc3e1e51c143e0cf66da1d4.
